---
title: Contributing
layout: default
output: bookdown::html_chapter
---

# Contributing

This manual has been developed in the open, and it wouldn't be nearly as good 
without your contributions. There are a number of ways you can help make the
manual even better:

* If you don't understand something, please 
  [let me know](mailto:tdhock5@gmail.com). Your feedback on what is confusing
  or hard to understand is valuable.

* If you spot a typo, feel free to edit the underlying page and send a pull 
  request. If you've never done this before, the process is very easy: 
  
    * Click "edit this page" on the left sidebar.
  
    * Make the changes using github's in-page editor and save.
    
    * Submit a pull request including a brief description of your changes: 
      "fixing typos" is perfectly adequate.
      
    * If you make significant changes, include the phrase "I assign the 
      copyright of this contribution to Toby Dylan Hocking" - 
	  I need this so I can publish the printed manual.
