View this manual online at https://rcdata.nau.edu/genomic-ml/animint2-manual/Ch00-preface.html

Compile this manual by typing =jekyll build= on the command
line. Jekyll/ruby versions tested include

#+BEGIN_SRC shell
thocking@silene:~/projects/animint-book(master)$ jekyll --version
jekyll 3.1.2
thocking@silene:~/projects/animint-book(master*)$ ruby --version
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
#+END_SRC

#+BEGIN_SRC shell
(base) tdhock@maude-MacBookPro:~/R/animint2(geom-oop)$ jekyll --version
jekyll 3.1.6
(base) tdhock@maude-MacBookPro:~/R/animint2(geom-oop)$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
#+END_SRC

Versions of R and packages are documented in [[file:_plugins/knit.R]]

pandoc known to work is [[https://github.com/jgm/pandoc/releases/tag/1.19.2][version=1.19.2.4]], does not work with 2.14.2

#+begin_src shell-script
wget https://github.com/jgm/pandoc/releases/download/1.19.2/pandoc-1.19.2-1-amd64.deb
mkdir pandoc
ar p pandoc-1.19.2-1-amd64.deb data.tar.gz | tar xvz --strip-components 2 -C pandoc

(base) tdhock@maude-MacBookPro:~/projects/animint2-manual(master*)$ /usr/bin/pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/tdhock/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

(base) tdhock@maude-MacBookPro:~/projects/animint2-manual(master*)$ pandoc --version
pandoc 2.14.2
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11,
citeproc 0.5, ipynb 0.1.0.1
User data directory: /home/tdhock/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
#+end_src

~/bin/pandoc is too new, created ./bin/pandoc symlink to old
/usr/bin/pandoc and then compile via =bash build.sh= which contains:

#+begin_src shell-script
PATH=bin:$PATH jekyll b
#+end_src

Also make sure that animint2-manual/_plugins/library (used for
interactive testing) is symlinked to animint2-manual/library (used for
rendering, could be confusing if they are different).

To edit Rmd in emacs try https://github.com/vspinu/polymode via
https://github.com/tdhock/dotfiles/blob/master/.emacs

** TODOs

- chapter with geom_abline + coord_equal for comparing baseline +
  proposed algos.
- setup travis?
- what to do about slow loading? split Rmd files so that there is only
  one animint in each? or recode the renderer so that it only loads
  when you scroll down and the animint div becomes visible?
- use http://rstudio.github.io/tufte/ or https://bookdown.org/ ?
- https://bitpay.com for accepting donations? or just create a bitcoin wallet?

** How to add a chapter

- Create ChXX-foo.Rmd
- Add a link in [[file:_layouts/default.html]]
- Add a paragraph/link in [[file:Ch00-preface.Rmd]]
- Add a paragraph/link in the preceding chapter.
- Rename following chapters and update links if necessary.
