View this manual online at https://rcdata.nau.edu/genomic-ml/animint2-manual/Ch00-preface.html

Compile this manual by typing =jekyll build= on the command
line. Jekyll/ruby versions tested include

#+BEGIN_SRC shell
thocking@silene:~/projects/animint-book(master)$ jekyll --version
jekyll 3.1.2
thocking@silene:~/projects/animint-book(master*)$ ruby --version
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
#+END_SRC

#+BEGIN_SRC shell
(base) tdhock@maude-MacBookPro:~/R/animint2(geom-oop)$ jekyll --version
jekyll 3.1.6
(base) tdhock@maude-MacBookPro:~/R/animint2(geom-oop)$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
#+END_SRC

Versions of R and packages are documented in [[file:_plugins/knit.R]]

To edit Rmd in emacs try https://github.com/vspinu/polymode via
https://github.com/tdhock/dotfiles/blob/master/.emacs

** TODOs

- chapter with geom_abline + coord_equal for comparing baseline +
  proposed algos.
- setup travis?
- what to do about slow loading? split Rmd files so that there is only
  one animint in each? or recode the renderer so that it only loads
  when you scroll down and the animint div becomes visible?
- use http://rstudio.github.io/tufte/ or https://bookdown.org/ ?
- https://bitpay.com for accepting donations? or just create a bitcoin wallet?

** How to add a chapter

- Create ChXX-foo.Rmd
- Add a link in [[file:_layouts/default.html]]
- Add a paragraph/link in [[file:Ch00-preface.Rmd]]
- Add a paragraph/link the preceding chapter.
- Rename following chapters and update links if necessary.
